import type { Config } from "tailwindcss";
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#faf9f3",
        surface: { DEFAULT: "#faf9f3", dim: "#dbdad4", bright: "#faf9f3", tint: "#516257", variant: "#e3e3dd" },
        "surface-container": { lowest: "#ffffff", low: "#f5f4ee", DEFAULT: "#efeee8", high: "#e9e8e2", highest: "#e3e3dd" },
        "on-surface": "#1b1c19",
        "on-surface-variant": "#434844",
        "inverse-surface": "#30312d",
        "inverse-on-surface": "#f2f1eb",
        "inverse-primary": "#b8cbbd",
        outline: "#737873",
        "outline-variant": "#c3c8c2",
        primary: { DEFAULT: "#021008", container: "#16261d", fixed: "#d4e7d9", "fixed-dim": "#b8cbbd" },
        "on-primary": "#ffffff",
        "on-primary-container": "#7c8e82",
        "on-primary-fixed": "#0f1f16",
        "on-primary-fixed-variant": "#3a4b40",
        secondary: { DEFAULT: "#566500", container: "#d7ee6b", fixed: "#d7ee6b", "fixed-dim": "#bbd152" },
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5b6b00",
        "on-secondary-fixed": "#181e00",
        "on-secondary-fixed-variant": "#404c00",
        tertiary: { DEFAULT: "#1b0700", container: "#3d1800", fixed: "#ffdbc8", "fixed-dim": "#ffb68b" },
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#cf7131",
        "on-tertiary-fixed": "#321200",
        "on-tertiary-fixed-variant": "#753400",
        error: { DEFAULT: "#ba1a1a", container: "#ffdad6" },
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        success: { DEFAULT: "#2C6B39", container: "#DCEBD8" },
        "ai-accent": "#7C3AED",
        cmd: { bg: "#0B1220", surface: "#111A2E", raised: "#17223C", border: "#223052" },
        ink: { dark: "#F1F5F9", light: "#0F172A", muted: "#94A3B8" },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Fraunces", "serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.1", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      borderRadius: { sm: "0.25rem", DEFAULT: "0.5rem", md: "0.75rem", lg: "1rem", xl: "1.5rem", full: "9999px", btn: "9999px", card: "1rem" },
      spacing: { gutter: "24px", margin: "32px", "table-row-height": "64px", "grid-texture": "32px" },
      boxShadow: { warm: "0 4px 20px rgba(22,38,29,0.06)", "warm-lg": "0 12px 40px rgba(22,38,29,0.12)" },
    },
  },
  plugins: [],
};
